#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🏗️👷 Analyzing and building your project before committing"

yarn lint-staged ||
(
  echo "❌😤 Lint-staged failed."
  false;
)

echo "✅ Pre-commit hook passed. Committing."
